name: Proofreading
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  CALL-workflow_Proofreading:
    uses: MIZOGUCHIKoki/TextLint-workflows/.github/workflows/proofreading_main.yml@master
    secrets:
      gh_token: ${{ secrets.ACCESS_TOKEN }}
