name: Proofreading
on:
  workflow_call:
    secrets:
      gh_token:
        required: true
        description: 'GITHUB_TOKEN'

jobs:
  RUN-workflow_Proofreading:
    if: (github.event.issue.pull_request != null) && github.event.comment.body == 'correction'
    runs-on: ubuntu-latest
    steps:
      - name: Github-Script
        uses: actions/github-script@v2
        id: set-target-branch
        with:
          github-token: ${{ secrets.gh_token }}
          result-encoding: string
          script: |
            const pull_request = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            return pull_request.data.head.ref
            
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.set-target-branch.outputs.result }}
          token: ${{ secrets.gh_token }}
      - name: Wget textlint system file
        run: |
          wget https://raw.githubusercontent.com/MIZOGUCHIKoki/TextLint-workflows/master/configuration-files/package.json
          wget https://raw.githubusercontent.com/MIZOGUCHIKoki/TextLint-workflows/master/configuration-files/.textlintrc.json
          wget https://raw.githubusercontent.com/MIZOGUCHIKoki/TextLint-workflows/master/configuration-files/toHTML.xsl
      - name: Setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install packages via packages.json
        run: |
          npm install
      - name: Install zsh
        run: |
          sudo apt-get install zsh
      - name: Correct
        run: |
          npx textlint --fix **/**.tex
        shell: zsh {0}
      - name: Remove useless files
        if: ${{ always() }}
        run: |
          rm -rf ConfigFiles node_modules package-lock.json package.json .textlintrc.json .gitconfig
      - name: Check changed files
        if: ${{ always() }}
        id: diffcheck
        run: |
          git diff >> diff.txt
          if [ -s diff.txt ];
          then
            echo "RESULT=1" >> $GITHUB_OUTPUT
          fi
          rm diff.txt
      - name: Commit to current branch
        if: ${{ always() && steps.diffcheck.outputs.RESULT == 1 }}
        run: |
          git branch -a
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Proofreading"
          git push
