name: TextLint
on: 
  workflow_call:
    secrets:
      gh_token:
        required: true
        description: 'GITHUB_TOKEN'
jobs:
  RUN-workflow[TextLint]:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.gh_token }}
          ref: ${{ github.head_ref }}
      - name: Clone textlint system file
        uses: actions/checkout@v3
        with:
          repository: MIZOGUCHIKoki/TextLint-workflows
          path: TextLint-workflows      
      - name: moved files
        run: | 
          cp -a ./TextLint-workflows/configuration-files/. ./
      - name: Setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install packages via packages.json
        run: |
          npm install
      - name: Install zsh
        run: |
          sudo apt-get install zsh
      - name: Run textlint
        run: |
            npx textlint -f checkstyle **/*.tex >> ./textlint.xml
        shell: zsh {0}
      - name: Report if textlint finds problems (master)
        if: ${{ failure() && github.event_name == 'push' }}
        run: cat ./textlint.xml
      - name: Report if textlint finds problems (other branches)
        if: ${{ failure() && github.event_name != 'push' }}
        run: |
            sudo apt-get install xsltproc libxml2-utils
            xmllint --format ./textlint.xml > ./ftextlint.xml
            sed 2i\<?xml-stylesheet\ type=text\/xsl\ href=./toHTML.xsl\ \?\> ./ftextlint.xml > ./ptextlint.xml
            sed -i 's/([^)]*)//g' ./ptextlint.xml
            sed -i 's/eslint.rules.//g' ./ptextlint.xml
            pwd_esc=$(pwd | sed 's/\//\\\//g')
            xsltproc --output body.html ./toHTML.xsl ptextlint.xml
            cat body.html | sed "s/${pwd_esc}/:memo: ./g" >> ./.body.html
            gh pr comment --body-file ./.body.html "${URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
